version = 0.1

[default.global.parameters]
stack_name = "carta-clara-mvp"
region = "us-west-2"

[default.deploy.parameters]
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "carta-clara-mvp"
image_repositories = []
parameter_overrides = "KnowledgeBaseId=\"PLACEHOLDER\" GuardrailId=\"PLACEHOLDER\" GuardrailVersion=\"DRAFT\" MultimodalModelId=\"us.anthropic.claude-sonnet-4-6\" TextModelId=\"us.anthropic.claude-sonnet-4-6\" FastModelId=\"us.amazon.nova-pro-v1:0\" PollyVoiceId=\"Lupe\""

[default.sync.parameters]
watch = true
