//
//  UIText.swift
//  Carta Clara
//
//  Centralized UI CHROME strings (button labels, screen titles, VoiceOver
//  hints, status messages).
//
//  ──────────────────────────────────────────────────────────────────────
//  SCOPE DECISION (logged in docs/worklog/riku.md, 2026-05-16):
//
//  The project iron rule says "Spanish copy in UI strings comes from API
//  responses — do not hardcode Spanish text in the iOS app." That rule
//  governs DOCUMENT CONTENT — summaries, section explanations, refusal text,
//  scam descriptions, packet copy — all of which are generated by the
//  backend, pass through Bedrock Guardrails, and are reviewed. The iOS app
//  NEVER composes that copy. Verify: every `*_es` content field rendered by
//  the views is read straight from a Codable model.
//
//  This file is the EXCEPTION it does not cover: static interface chrome
//  (the word on a button, a screen title). The customer is a Spanish-
//  speaking grandmother (TENETS.md §5) — an English-only chrome layer fails
//  the grandma test outright. Chrome must be Spanish. It is centralized in
//  ONE file so it is trivial to review or move to a String Catalog later.
//
//  If Claudio wants chrome to also come from the backend, this is the single
//  file to change. Flagged for review.
//  ──────────────────────────────────────────────────────────────────────
//

import Foundation

/// All static UI chrome strings. Spanish primary; an English subtitle is shown
/// only where a bilingual cue aids a helper (e.g., a granddaughter on the phone).
enum UIText {

    // MARK: Brand
    static let appName = "Carta Clara"
    static let tagline = "Entiende tu carta. Con calma."

    // MARK: Splash
    static let getStarted = "Empezar"
    static let tryDemoButton = "Usar documento de demostración"
    static let demoDocMissingTitle = "Documento de demostración no disponible"
    static let demoDocMissingBody = "El documento de demostración todavía no está incluido en la app. Usa la cámara o una foto guardada."
    static let disclaimerButton = "Lo que esta app no hace"
    static let disclaimerTitle = "Información, no consejo legal"
    /// The disclaimer body. This is a fixed, non-legal-advice product
    /// statement (the inverse of giving advice) — it is product chrome, and
    /// it mirrors TENETS.md §3 and the Press Release verbatim in intent.
    static let disclaimerBody = """
    Carta Clara te explica lo que dice un documento, qué es urgente y qué \
    preguntas hacerle a un abogado.

    Carta Clara NO da consejo legal. No le responde a USCIS, a la corte ni a \
    ICE. No te dice qué decir, qué admitir ni si calificas para algo.

    Cuando una pregunta necesita un abogado, esta app se detiene y te conecta \
    con ayuda legal gratis.
    """
    static let disclaimerClose = "Entiendo"

    // MARK: Camera
    static let cameraTitle = "Toma una foto del documento"
    static let cameraHint = "Pon la carta sobre una mesa con buena luz."
    static let captureButton = "Tomar foto"
    static let captureA11y = "Tomar foto del documento"
    static let captureA11yHint = "Activa la cámara y captura la carta."
    static let pickFromLibrary = "Elegir una foto guardada"
    static let cameraDeniedTitle = "La cámara está apagada"
    static let cameraDeniedBody = "Para tomar una foto, activa el permiso de cámara en Ajustes. También puedes elegir una foto guardada."
    static let openSettings = "Abrir Ajustes"
    static let retake = "Tomar otra"
    static let usePhoto = "Usar esta foto"

    // MARK: Redaction animation
    static let redactionTitle = "Protegiendo tu información"
    static let redactionCaption = "Tapamos tus datos antes de enviar nada."
    static let redactionDone = "Tu información está protegida."
    static let processing = "Leyendo el documento…"
    /// VoiceOver announcement posted when masking finishes.
    static let redactionA11yAnnouncement = "Tu información personal fue tapada. El documento ya está protegido."
    /// The PII categories shown being masked. These are field-CATEGORY labels
    /// (UI chrome), not values — no synthetic or real PII is ever displayed.
    static let redactionFields: [String] = [
        "Nombre", "Número A", "Dirección", "Fecha de nacimiento", "Número de caso"
    ]
    static let redactedTag = "PROTEGIDO"

    // MARK: Results
    static let resultsTitle = "Tu documento"
    static let readingLevelLabel = "Nivel de lectura"
    static let readingLevelBeginner = "Sencillo"
    static let readingLevelIntermediate = "Normal"
    static let readingLevelFull = "Completo"
    static let askButton = "Preguntar sobre este documento"
    static let helpRespondButton = "Ayúdame a responder"
    static let legalHelpButton = "Buscar ayuda legal gratis"
    static let playSummary = "Escuchar el resumen"
    static let pauseSummary = "Pausar el resumen"
    static let sectionExpand = "Ver más"
    static let sectionCollapse = "Ver menos"
    static let citationsLabel = "Fuentes"
    static let demoBadge = "DOCUMENTO DE DEMOSTRACIÓN"

    // MARK: Questions card (results)
    // NOTE: The /scan contract carries no "questions" array — the questions
    // for the lawyer live in the /scan/packet response (`questions_for_lawyer_es`).
    // This card is therefore a routing card to the Response Preparation Packet,
    // not a content card. Its copy is UI chrome. (See worklog 2026-05-16.)
    static let questionsCardTitle = "Preguntas para tu abogado"
    static let questionsCardBody = "Prepara las preguntas correctas antes de tu cita con un abogado. Las incluimos en tu paquete de preparación."
    static let questionsCardCTA = "Crear mi paquete"

    // MARK: Ask / chat
    static let askTitle = "Preguntar"
    static let askPlaceholder = "Escribe tu pregunta…"
    static let micButton = "Mantén presionado para hablar"
    static let micRecording = "Grabando… suelta para enviar"
    static let micA11y = "Botón de voz"
    static let micA11yHint = "Mantén presionado para grabar tu pregunta. Suelta para enviarla."
    static let sendButton = "Enviar"
    static let askEmptyState = "Haz una pregunta sobre tu documento. Puedes hablar o escribir."
    static let askThinking = "Pensando…"
    static let askVoiceQuestion = "Pregunta por voz"
    static let askYou = "Tú"
    static let askAssistant = "Carta Clara"
    static let micPermissionDeniedTitle = "El micrófono está apagado"
    static let micPermissionDeniedBody = "Para preguntar con tu voz, activa el permiso del micrófono en Ajustes. También puedes escribir tu pregunta."
    static let refusalCounterA11y = "Contador de respuestas no dadas"
    static let refusalCounterA11yHint = "Toca para ver qué preguntas la app no contesta y por qué."

    // MARK: Refusal log
    static let refusalLogTitle = "Lo que esta app no contesta"
    static let refusalLogIntro = "Cuando una pregunta necesita un abogado, la app no la contesta. Esa es la idea."
    static let refusalLogEmpty = "Todavía no hay ninguna. Cuando la app se detenga ante una pregunta legal, aparecerá aquí."

    // MARK: Response packet
    static let packetTitle = "Paquete de preparación"
    static let packetGenerating = "Preparando tu paquete…"
    static let packetShare = "Compartir o imprimir"
    static let packetShareA11y = "Compartir o imprimir el paquete de preparación"
    static let packetShareA11yHint = "Comparte o imprime este paquete para tu cita de ayuda legal."
    static let packetPreparingShare = "Preparando el documento…"

    // MARK: Legal help
    static let legalHelpTitle = "Ayuda legal gratis"
    static let legalHelpIntro = "Estas organizaciones ofrecen consultas gratis. Llama o visita."
    static let callButton = "Llamar"
    static let directionsButton = "Cómo llegar"
    static let freeBadge = "GRATIS"
    static let legalHelpVerifyNote = "Confirma los horarios y la dirección llamando antes de ir. La información de contacto puede cambiar."
    static let legalHelpHoursLabel = "Horario"
    static let legalHelpLanguagesLabel = "Idiomas"

    // MARK: Response packet section headers (chrome — content is from the API)
    static let packetWhatItSays = "Qué dice este documento"
    static let packetDeadline = "Tu fecha límite"
    static let packetDocuments = "Documentos para reunir"
    static let packetExtension = "Solicitud para pedir más tiempo"
    static let packetPhoneScript = "Qué decir cuando llames"
    static let packetQuestions = "Preguntas para tu abogado"
    static let packetCoverSheet = "Hoja de presentación"
    static let packetError = "No pudimos crear el paquete. Inténtalo otra vez."

    // MARK: Errors / empty / offline
    static let errorTitle = "Algo salió mal"
    static let errorGeneric = "No pudimos terminar. Revisa tu conexión e inténtalo otra vez."
    static let errorOffline = "No hay conexión a internet. Conéctate e inténtalo otra vez."
    static let errorRetry = "Intentar otra vez"
    static let errorNotConfigured = "La app aún no está conectada al servidor. Falta el API_BASE_URL en Configuration.plist."
    static let loading = "Cargando…"

    // MARK: Reading-level display helper
    static func readingLevelName(_ level: ReadingLevel) -> String {
        switch level {
        case .beginner: return readingLevelBeginner
        case .intermediate: return readingLevelIntermediate
        case .full: return readingLevelFull
        }
    }
}
